```mermaid
graph TD
TwitterStream -->|jar executable| EventHub
EventHub --> |input|ASA[Azure Stream Analytics]
ASA --> |query step|Sql1[UserMention-Word Counts]
ASA --> |query step|Sql2[UserMention-HashTag Counts]
ASA --> |query step|Sql3[HashTag-Word Counts]
ASA --> |query step|Sql4[Popular HashTags that lost popularity]
Sql1 --> |sql-output|Sql1out[UserMentionWordGlobalWindowCounts]
Sql2 --> |sql-output|Sql2out[HashTagWordGlobalWindowCounts]
Sql3 --> |sql-output|Sql3out[HashTagUserMentionGlobalWindowCounts]
Sql4 --> |sql-output|Sql4out[PopularHashTagsThatAreNoLongerMentioned]
```